## 4. Soru 

- Forward propagation için, input olarak şu X matrisini verin (tensöre çevirmeyi unutmayın):

    $X = \begin{bmatrix}
        1 & 2 & 3\\
        4 & 5 & 6
    \end{bmatrix}$

    Satırlar veriler (sample'lar), kolonlar öznitelikler (feature'lar).

- Bir adet hidden layer olsun ve içinde tanh aktivasyon fonksiyonu olsun.

- Hidden layer'da 50 nöron olsun.

- Bir adet output layer olsun, tek nöronu olsun ve içinde sigmoid aktivasyon fonksiyonu olsun.


* Kütüphanelerin import edilmesi

In [1]:
import pandas as pd
import numpy as np
import seaborn as sbn
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

* Tensörün oluşturulması

In [2]:
x = np.arange(1,7).reshape(2,3)
x = torch.tensor(x, dtype=torch.float32)

In [3]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

* Sinir ağının oluşturulması ve seed değerinin set edilmesi

#### 4.1 Yukarıdaki yapay sinir ağını çalıştırmadan önce pytorch için Seed değerini 1 olarak set edin, kodu aşağıdaki kod bloğuna ve altına da sonucu yapıştırın

In [4]:
seed_value = 1
torch.manual_seed(seed_value)

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.hidden_layer = nn.Linear(input_size, hidden_size)
        self.output_layer = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = torch.flatten(x, 1)
        hidden_res = self.tanh_func(self.hidden_layer(x))
        output = self.sigmoid_func(self.output_layer(hidden_res))
        return output
    
    def sigmoid_func(self, x):
        return 1 / (1 + torch.exp(-x))
    
    def tanh_func(self, x):
        return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

input_size = x.shape[1]
hidden_size = 50
output_size = 1
model = MLP(input_size, hidden_size, output_size)

output = model(x)
print(output)


tensor([[0.4892],
        [0.5566]], grad_fn=<MulBackward0>)


#### 4.2 Yukarıdaki yapay sinir ağını çalıştırmadan önce Seed değerini öğrenci numaranız olarak değiştirip, kodu aşağıdaki kod bloğuna ve altına da sonucu yapıştırın

In [5]:
seed_value = 190401037
torch.manual_seed(seed_value)

class MLP(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(MLP, self).__init__()
        self.hidden_layer = nn.Linear(input_size, hidden_size)
        self.output_layer = nn.Linear(hidden_size, output_size)

    def forward(self, x):
        x = torch.flatten(x, 1)
        hidden_res = self.tanh_func(self.hidden_layer(x))
        output = self.sigmoid_func(self.output_layer(hidden_res))
        return output
    
    def sigmoid_func(self, x):
        return 1 / (1 + torch.exp(-x))
    
    def tanh_func(self, x):
        return (torch.exp(x) - torch.exp(-x)) / (torch.exp(x) + torch.exp(-x))

input_size = x.shape[1]
hidden_size = 50
output_size = 1
model = MLP(input_size, hidden_size, output_size)

output = model(x)
print(output)


tensor([[0.3700],
        [0.3356]], grad_fn=<MulBackward0>)
